# FreshMart Supermarket Demo - Metadata
# This file enables the fabric-demo automation tool to validate compatibility
# Version: 1.0
# Generated: January 2026

metadata:
  name: FreshMart Supermarket Demo
  version: "1.0"
  created: "2026-01-07"
  author: Fabric Ontology Demo Agent
  specVersion: "3.3"

demo:
  company: FreshMart Supermarkets
  industry: Retail
  domain: Grocery Supply Chain
  description: Supply chain traceability and food safety ontology for supermarket operations
  
  useCases:
    - Food Recall Traceability
    - Supplier Quality Analysis
    - Cold Chain Monitoring
    - Compliance Audit Trails
    - Inventory Optimization

  audience:
    - Operations Managers
    - Supply Chain Analysts
    - Compliance Officers
    - IT/Data Teams

ontology:
  file: Ontology\freshmart.ttl
  namespace: http://freshmart.com/ontology#
  
  entities:
    - name: Store
      key: StoreId
      keyType: string
      hasTimeseries: true
      
    - name: Product
      key: ProductId
      keyType: string
      hasTimeseries: false
      
    - name: Supplier
      key: SupplierId
      keyType: string
      hasTimeseries: false
      
    - name: ProductBatch
      key: BatchId
      keyType: string
      hasTimeseries: true
      
    - name: Category
      key: CategoryId
      keyType: string
      hasTimeseries: false
      
    - name: Employee
      key: EmployeeId
      keyType: string
      hasTimeseries: false
      
    - name: PurchaseOrder
      key: OrderId
      keyType: string
      hasTimeseries: false
      
    - name: QualityInspection
      key: InspectionId
      keyType: string
      hasTimeseries: false

  relationships:
    - name: BELONGS_TO
      source: Product
      target: Category
      
    - name: SUPPLIED_BY
      source: Product
      target: Supplier
      
    - name: STOCKS
      source: Store
      target: Product
      
    - name: EMPLOYS
      source: Store
      target: Employee
      
    - name: CONTAINS
      source: ProductBatch
      target: Product
      
    - name: RECEIVED_AT
      source: ProductBatch
      target: Store
      
    - name: ORDERED_BY
      source: PurchaseOrder
      target: Store
      
    - name: FULFILLED_BY
      source: PurchaseOrder
      target: Supplier
      
    - name: INSPECTED
      source: QualityInspection
      target: ProductBatch
      
    - name: PERFORMED_BY
      source: QualityInspection
      target: Employee

  statistics:
    entityCount: 8
    relationshipCount: 10
    timeseriesEntityCount: 2
    maxTraversalHops: 5

data:
  lakehouse:
    tables:
      - name: DimStore
        file: Data\Lakehouse\DimStore.csv
        rowCount: 12
        
      - name: DimProduct
        file: Data\Lakehouse\DimProduct.csv
        rowCount: 28
        
      - name: DimSupplier
        file: Data\Lakehouse\DimSupplier.csv
        rowCount: 10
        
      - name: DimProductBatch
        file: Data\Lakehouse\DimProductBatch.csv
        rowCount: 45
        
      - name: DimCategory
        file: Data\Lakehouse\DimCategory.csv
        rowCount: 8
        
      - name: DimEmployee
        file: Data\Lakehouse\DimEmployee.csv
        rowCount: 24
        
      - name: FactPurchaseOrder
        file: Data\Lakehouse\FactPurchaseOrder.csv
        rowCount: 35
        
      - name: FactQualityInspection
        file: Data\Lakehouse\FactQualityInspection.csv
        rowCount: 40
        
      - name: FactStoreInventory
        file: Data\Lakehouse\FactStoreInventory.csv
        rowCount: 70

  eventhouse:
    tables:
      - name: StoreTelemetry
        file: Data\Eventhouse\StoreTelemetry.csv
        rowCount: 54
        keyColumn: StoreId
        timestampColumn: Timestamp
        metrics:
          - FootTraffic
          - SalesVelocity
          - AvgTransactionValue
          
      - name: BatchTelemetry
        file: Data\Eventhouse\BatchTelemetry.csv
        rowCount: 63
        keyColumn: BatchId
        timestampColumn: Timestamp
        metrics:
          - StorageTemperature
          - Humidity
          - DaysToExpiry

bindings:
  file: Bindings\bindings.yaml
  lakehouseInstructions: Bindings\lakehouse-binding.md
  eventhouseInstructions: Bindings\eventhouse-binding.md

documentation:
  readme: README.md
  ontologyStructure: ontology-structure.md
  demoQuestions: demo-questions.md
  ontologyDiagram: Ontology\ontology-diagram-slide.html

validation:
  checksums:
    ontologyFile: null  # Generated on validation
    bindingsFile: null  # Generated on validation
    
  requiredFiles:
    - README.md
    - .demo-metadata.yaml
    - demo-questions.md
    - ontology-structure.md
    - Bindings\bindings.yaml
    - Bindings\lakehouse-binding.md
    - Bindings\eventhouse-binding.md
    - Ontology\freshmart.ttl
    - Ontology\ontology-diagram-slide.html
    - Data\Lakehouse\DimStore.csv
    - Data\Lakehouse\DimProduct.csv
    - Data\Lakehouse\DimSupplier.csv
    - Data\Lakehouse\DimProductBatch.csv
    - Data\Lakehouse\DimCategory.csv
    - Data\Lakehouse\DimEmployee.csv
    - Data\Lakehouse\FactPurchaseOrder.csv
    - Data\Lakehouse\FactQualityInspection.csv
    - Data\Lakehouse\FactStoreInventory.csv
    - Data\Eventhouse\StoreTelemetry.csv
    - Data\Eventhouse\BatchTelemetry.csv

compatibility:
  fabricDemoCliVersion: ">=1.0.0"
  fabricApiVersion: "2025-01"
  ontologySpecVersion: "3.3"
