schema_version: '1.0'
setup_id: 998ddca4-0892-4dad-b699-c2819cea31de
demo_name: AutoManufacturing-SupplyChain
workspace_id: bf5fab96-5f75-44a9-a8e2-850ad6ea59ce
started_at: '2026-01-14T00:49:21.548005+00:00'
status: in_progress
steps:
  validate:
    status: completed
    started_at: '2026-01-14T00:49:21.550350+00:00'
    completed_at: '2026-01-14T00:49:21.556161+00:00'
  create_lakehouse:
    status: completed
    artifact_id: 6ce5da4c-8ff3-463c-82d3-8b90e99d7d4b
    artifact_name: AutoManufacturing_SupplyChain_Lakehouse
    started_at: '2026-01-14T00:49:21.561449+00:00'
    completed_at: '2026-01-14T00:49:32.567696+00:00'
  upload_files:
    status: completed
    started_at: '2026-01-14T00:49:32.575163+00:00'
    completed_at: '2026-01-14T00:49:38.414906+00:00'
    details:
      uploaded:
      - DimAssembly.csv
      - DimComponent.csv
      - DimFacility.csv
      - DimProductionOrder.csv
      - DimSupplier.csv
      - DimVehicle.csv
      - EdgeAssemblyComponent.csv
      - EdgeShipmentComponent.csv
      - EdgeShipmentDestination.csv
      - EdgeShipmentOrigin.csv
      - FactQualityEvent.csv
      - FactShipment.csv
      skipped: []
  load_tables:
    status: in_progress
    started_at: '2026-01-14T00:49:38.422747+00:00'
resources:
  lakehouse:
    id: 6ce5da4c-8ff3-463c-82d3-8b90e99d7d4b
    name: AutoManufacturing_SupplyChain_Lakehouse
